### ISSUE TITLE
DNS Records not being created

### ISSUE THREAD

**Issue by samstride** [caddy-dns/google-domains#2]
Hi,

Thanks for making this available.

My setup:

```sh
#Caddyfile
https://sub.domain.com {
        tls {
                dns google_domains <token>
        }
        reverse_proxy 192.168.9.146:8000
}
```

```sh
xcaddy version
v0.3.4 h1:eQAZPEQqyLY7S9+rfdvx/Zs/a3VNwo+f5d2BR6UNvig=

go version
go version go1.20.4 linux/amd64

xcaddy build \
    --with github.com/mholt/caddy-dynamicdns \
    --with github.com/caddy-dns/google-domains
    
sudo dpkg-divert --divert /usr/bin/caddy.default --rename /usr/bin/caddy
sudo mv ./caddy /usr/bin/caddy.custom
sudo update-alternatives --install /usr/bin/caddy caddy /usr/bin/caddy.default 10
sudo update-alternatives --install /usr/bin/caddy caddy /usr/bin/caddy.custom 50

sudo systemctl stop caddy

sudo systemctl start caddy
```

I don't see any errors in the logs.

I cannot see any records for the subdomain being created in google domains.

Your help would be appreciated.

Thanks.

**Comment by mholt** [comment]
Are you sure a certificate is even needed to begin with? If Caddy already has a certificate it won't create a new one.

If you could please enable debug mode and post the logs when running Caddy, that'd be useful.

**Comment by samstride** [comment]
Hi,

Yes, the cert was initially issued using vanilla caddy.

Here are the logs with debug mode enabled:

```sh
May 27 10:47:45 machine-x caddy[373163]: {"level":"info","ts":1685141265.7679894,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["sub.domain.com"]}
May 27 10:47:45 machine-x caddy[373163]: {"level":"debug","ts":1685141265.7682087,"logger":"tls","msg":"loading managed certificate","domain":"sub.domain.com","expiration":1691476635,"issuer_key":"acme-v02.api.letsencrypt.org-directory","storage":"FileStorage:/var/lib/caddy/.local/share/caddy"}
May 27 10:47:45 machine-x caddy[373163]: {"level":"debug","ts":1685141265.7683654,"logger":"tls.cache","msg":"added certificate to cache","subjects":["sub.domain.com"],"expiration":1691476635,"managed":true,"issuer_key":"acme-v02.api.letsencrypt.org-directory","hash":"1d40b191eabe0ac119546f025bbe506a5a09206202a8c3cdacb6a65794e81835","cache_size":1,"cache_capacity":10000}
May 27 10:47:45 machine-x caddy[373163]: {"level":"debug","ts":1685141265.7683802,"logger":"events","msg":"event","name":"cached_managed_cert","id":"d461b88b-2f33-4b4c-8855-bfa30356e9ad","origin":"tls","data":{"sans":["sub.domain.com"]}}
May 27 10:47:45 machine-x caddy[373163]: {"level":"info","ts":1685141265.7684307,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000287110"}
May 27 10:47:45 machine-x caddy[373163]: {"level":"info","ts":1685141265.7685082,"msg":"autosaved config (load with --resume flag)","file":"/var/lib/caddy/.config/caddy/autosave.json"}
May 27 10:47:45 machine-x caddy[373163]: {"level":"info","ts":1685141265.7685344,"logger":"admin.api","msg":"load complete"}
May 27 10:47:45 machine-x caddy[373163]: {"level":"info","ts":1685141265.7695656,"logger":"tls","msg":"finished cleaning storage units"}
May 27 10:47:45 machine-x caddy[373163]: {"level":"info","ts":1685141265.7695808,"logger":"admin","msg":"stopped previous server","address":"localhost:2019"}
May 27 10:47:45 machine-x systemd[1]: Reloaded Caddy.
```

Briefly, I was using caddy to generate certs for my sub domain and I would configure dynamic dns for the sub domain using the Google Domans dynamic dns feature and update the A record using their REST API every time my ISP ip changed.

My understanding is that I can now automate all that using the dynamic dns module and that the A record would be automatically created/updated?

Thanks.

**Comment by mholt** [comment]
Thanks -- it does look like Caddy is already reusing an existing cert, so it doesn't do the DNS challenge (yet) -- not until it needs to renew.

> My understanding is that I can now automate all that using the dynamic dns module and that the A record would be automatically created/updated?

Yeah so the great thing about the DNS challenge is that your A/AAAA records don't matter. Neither does connectivity to your server from the outside. The DNS challenge is very flexible that way.

(Closing, but feel free to continue discussion if needed.)

**Comment by samstride** [comment]
@mholt . Thanks. Hmmm, this part is still not working:

```
This is a simple Caddy app that keeps your DNS pointed to your machine; especially useful if your IP address is not static.
```

My understanding is that an A record would be setup automatically to point to my machine? Am I missing something?

This is all I have in my Caddyfile:

```sh
https://sub.domain.com {
        tls {
                dns google_domains <token>
        }
        reverse_proxy 192.168.9.146:8000
}
```

**Comment by mholt** [comment]
@samstride

This config:

```
        tls {
                dns google_domains <token>
        }
```

will get your certificate using the DNS challenge, with your domain's nameservers at Google Domains.

You quote the readme of the Dynamic DNS project:

> This is a simple Caddy app that keeps your DNS pointed to your machine; especially useful if your IP address is not static.

which is a separate repo. Are you trying to use the Dynamic DNS plugin instead of getting a certificate with the DNS challenge? I'm not sure what your question was about.

Note that the readme on _this repo_ says (in bold):

> **Unlike most DNS provider modules for Caddy, this module works ONLY for ACME DNS challenges, due to limitations in the Google Domains API, which is designed only for manipulating TXT records for the DNS challenge.**

So you cannot use this Google Domains module with the Dynamic DNS plugin, unfortunately. You can request that Google add support for that.

**Comment by samstride** [comment]
@mholt , yes, I am trying to use the Dynamic DNS plugin. Sorry about the confusion.

Ok, I did see the part in bold but my bad I guess, failed to realize that they both don't work together.

Things are clearer to me now.

BTW, google domains does have a separate API for Dynamic DNS.

```
https://support.google.com/domains/answer/6147083?hl=en

Update your Dynamic DNS record with the API
Dynamic DNS client software automatically updates your dynamic DNS record. You can perform manual updates with the API by making a POST request or GET to the following URL:
domains.google.com/nic/update
The API requires HTTPS. Here’s an example request:
https://username:password@domains.google.com/nic/update?hostname=subdomain.yourdomain.com&myip=1.2.3.4
```

Have been doing that via a script. I do not like this approach because the username and password is in the URL.

Will keep an eye to see if google will update their APIs.

Once again, thank you for taking the time to respond.

**Comment by mholt** [comment]
Yeah, I saw that. But like you said it's not great :)
